const $=id=>document.getElementById(id),chosen=new Map();
let catalog=null,kind='structure',state={},selectedSeed=null,manualResults=[];
const fields=['anchor','radius','x','z','threads','seed','limit','maxMatches','cluster'];
const names={ancient_cities:'Ancient city',buried_treasures:'Buried treasure',desert_pyramids:'Desert pyramid',igloos:'Igloo',jungle_temples:'Jungle temple',mineshafts:'Mineshaft',ocean_monuments:'Ocean monument',ocean_ruins:'Ocean ruins',pillager_outposts:'Pillager outpost',ruined_portals:'Ruined portal',shipwrecks:'Shipwreck',strongholds:'Stronghold',swamp_huts:'Swamp hut',trail_ruins:'Trail ruins',trial_chambers:'Trial chamber',villages:'Village',woodland_mansions:'Woodland mansion',abandoned_camp:'Abandoned camp'};
const label=k=>names[k]||k.split('_').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error)}
async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),obj=await r.json();if(!r.ok)throw Error(obj.error);return obj}
function save(){localStorage.setItem('seed-scout-settings',JSON.stringify({fields:Object.fromEntries(fields.map(k=>[k,$(k).value])),chosen:[...chosen.values()]}))}
try{const saved=JSON.parse(localStorage.getItem('seed-scout-settings'));if(saved){for(const [k,v] of Object.entries(saved.fields))if($(k))$(k).value=v;for(const f of saved.chosen)chosen.set(`${f.kind}:${f.key}`,f)}}catch{}
function renderFeatures(){if(!catalog)return;const list=kind==='structure'?catalog.sets:catalog.biomes,filter=$('filter').value.toLowerCase();$('features').innerHTML=list.filter(k=>label(k).toLowerCase().includes(filter)).map(k=>`<label class="feature-row ${chosen.has(`${kind}:${k}`)?'selected':''}"><input type="checkbox" data-key="${k}" ${chosen.has(`${kind}:${k}`)?'checked':''}><span>${escape(label(k))}</span><span class="badge">${kind==='structure'?'START CHECK':'SAMPLED'}</span></label>`).join('')||'<p class="loading">No matching features.</p>';document.querySelectorAll('[data-key]').forEach(el=>el.onchange=()=>{const id=`${kind}:${el.dataset.key}`;if(el.checked)chosen.set(id,{kind,key:el.dataset.key,radius:Number($('radius').value)});else chosen.delete(id);renderFeatures();renderChosen();save()})}
function renderChosen(){$('selection-count').textContent=`${chosen.size} selected`;$('chosen').innerHTML=[...chosen.entries()].map(([id,f])=>`<div class="chosen-row"><span>${escape(label(f.key))}</span><input type="number" min="32" max="8000" value="${f.radius}" aria-label="Distance for ${escape(label(f.key))}" data-distance="${id}"><small>blocks</small><button data-remove="${id}" aria-label="Remove ${escape(label(f.key))}">×</button></div>`).join('');document.querySelectorAll('[data-distance]').forEach(el=>el.onchange=()=>{chosen.get(el.dataset.distance).radius=Number(el.value);save()});document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{chosen.delete(el.dataset.remove);renderChosen();renderFeatures();save()});$('start').disabled=!catalog||state.running||!chosen.size;$('inspect').disabled=!catalog||!chosen.size}
function request(){return {...Object.fromEntries(fields.map(k=>[k,$(k).value])),features:[...chosen.values()]}}
for(const f of fields)$(f).addEventListener('change',()=>{if(f==='radius'){for(const entry of chosen.values())entry.radius=Number($('radius').value);renderChosen()}$('coordinates').hidden=$('anchor').value!=='custom';save()});$('coordinates').hidden=$('anchor').value!=='custom';
document.querySelectorAll('[data-kind]').forEach(el=>el.onclick=()=>{kind=el.dataset.kind;document.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('active',b===el));renderFeatures()});$('filter').oninput=renderFeatures;
document.querySelectorAll('[data-preset]').forEach(el=>el.onclick=()=>{if(!catalog)return;chosen.clear();const pair=el.dataset.preset==='starter'?['villages','cherry_grove']:el.dataset.preset==='island'?['villages','mushroom_fields']:['villages','trial_chambers'];for(const key of pair){const k=catalog.sets.includes(key)?'structure':'biome';chosen.set(`${k}:${key}`,{kind:k,key,radius:Number($('radius').value)})}renderFeatures();renderChosen();save()});
$('start').onclick=async()=>{try{save();const response=await api('/api/start',request());state.running=true;manualResults=[];$('seed').value=response.seed;selectedSeed=null;notice(`Searching from seed ${response.seed}.`);await poll()}catch(e){notice(e.message,true)}};
$('stop').onclick=async()=>{try{await api('/api/stop',{});notice('Stopping after the current checks…');$('stop').disabled=true}catch(e){notice(e.message,true)}};
$('resume').onclick=()=>{if(state.nextSeed){$('seed').value=state.nextSeed;$('start').click()}};
$('inspect').onclick=async()=>{const seed=$('inspect-seed').value.trim();if(!seed)return notice('Enter a numeric Minecraft seed to check.',true);$('inspect').disabled=true;notice('Checking your selected features…');try{const result=await api('/api/inspect',{...request(),seed});if(!result.match)notice('That seed does not match these conditions.');else{manualResults=manualResults.filter(r=>r.seed!==result.seed);manualResults.unshift(result);selectedSeed=result.seed;renderResults();drawMap(result);notice('Seed matches your selected conditions.')}}catch(e){notice(e.message,true)}finally{renderChosen()}};
function allResults(){return [...manualResults,...(state.results||[])].filter((r,i,a)=>a.findIndex(x=>x.seed===r.seed)===i)}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({...state,results:allResults()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='seed-scout-results.json';a.click();URL.revokeObjectURL(url)};
$('quit').onclick=async()=>{await api('/api/shutdown',{});notice('App closed. You can close this tab.');clearInterval(timer)};
async function copySeed(seed,el){try{await navigator.clipboard.writeText(seed);el.textContent='Copied ✓';setTimeout(()=>el.textContent='Copy seed',1400)}catch{notice(`Seed: ${seed}`)}}
function renderResults(){const results=allResults();if(!results.length){selectedSeed=null;$('map').className='map-empty';$('map').innerHTML='<div class="empty-icon">⌖</div><h3>A good world is out there.</h3><p>Select your features and start a search.</p>';$('map-title').textContent='Your future neighbourhood';$('map-scale').textContent='Feature positions';$('results').innerHTML='<p class="empty-results">Matching seeds will appear here as they’re found.</p>';return}if(!results.some(r=>r.seed===selectedSeed)){selectedSeed=results[0].seed;drawMap(results[0])}$('results').innerHTML=results.map(r=>`<article class="result-card ${r.seed===selectedSeed?'active':''}" data-seed="${r.seed}"><div class="result-top"><span class="seed-number">${r.seed}</span><button class="copy" data-copy="${r.seed}">Copy seed</button></div><div class="result-features">${r.features.map(f=>`<span class="feature-chip">${escape(label(f.key))} · ${f.distance.toLocaleString()} blocks</span>`).join('')}</div><div class="result-meta">Spawn region: ${r.spawnX}, ${r.spawnZ} · ${r.features.filter(f=>f.kind==='structure').length} structure starts confirmed</div></article>`).join('');document.querySelectorAll('[data-copy]').forEach(el=>el.onclick=e=>{e.stopPropagation();copySeed(el.dataset.copy,el)});document.querySelectorAll('[data-seed]').forEach(el=>el.onclick=()=>{selectedSeed=el.dataset.seed;renderResults();drawMap(results.find(r=>r.seed===selectedSeed))})}
function drawMap(result){if(!result)return;const features=result.features,extent=Math.max(100,...features.map(f=>Math.max(Math.abs(f.x-result.anchorX),Math.abs(f.z-result.anchorZ))))*1.35,scale=118/extent,cx=210,cy=147;
let svg=`<svg viewBox="0 0 420 296" role="img" aria-label="Feature position map for seed ${result.seed}"><defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0H0V28" fill="none" stroke="#344830" stroke-width=".5"/></pattern></defs><rect width="420" height="296" fill="url(#grid)"/><circle cx="${cx}" cy="${cy}" r="118" fill="#b0d48705" stroke="#617849" stroke-dasharray="3 5"/><path d="M${cx-6} ${cy}h12m-6 -6v12" stroke="#e9c484" stroke-width="2"/><text x="20" y="25" fill="#e9c484" font-size="9">Centre: ${result.anchorX}, ${result.anchorZ}</text><text x="390" y="25" fill="#a6b39e" font-size="10">N ↑</text>`;
features.forEach((f,i)=>{const px=cx+(f.x-result.anchorX)*scale,py=cy+(f.z-result.anchorZ)*scale;svg+=`<line x1="${cx}" y1="${cy}" x2="${px}" y2="${py}" stroke="#66844b" stroke-opacity=".35"/><circle cx="${px}" cy="${py}" r="5" fill="${f.kind==='biome'?'#8dc8d1':'#c4e58c'}" stroke="#172019" stroke-width="2"><title>${escape(label(f.key))}: X ${f.x}, Y ${f.y}, Z ${f.z}. ${escape(f.confidence)}</title></circle><text x="${px>cx?px-8:px+8}" y="${py-9-(i%2)*3}" text-anchor="${px>cx?'end':'start'}" fill="#d4e6c5" font-size="9">${escape(label(f.key))}</text>`});svg+=`<path d="M20 275h55m-55 -3v6m55 -6v6" stroke="#95a787"/><text x="20" y="264" fill="#95a787" font-size="8">${Math.round(55/scale)} blocks</text></svg>`;$('map').className='map-drawing';$('map').innerHTML=svg;$('map-title').textContent=`Seed ${result.seed}`;$('map-scale').textContent='Hover markers for coordinates'}
async function poll(){try{const fresh=await(await fetch('/api/status')).json();if(fresh.catalog&&!catalog){catalog=fresh.catalog;for(const [id,f] of chosen)if(!(f.kind==='structure'?catalog.sets:catalog.biomes).includes(f.key))chosen.delete(id);if(!chosen.size)chosen.set('structure:villages',{kind:'structure',key:'villages',radius:Number($('radius').value)});renderFeatures();renderChosen();notice('Ready. Choose features, then start searching.')}if(state.running&&!fresh.running&&!fresh.error)notice(`Search finished: ${fresh.matches||0} matches from ${fresh.tested||0} checked seeds.`);state=fresh;$('tested').textContent=Number(state.tested||0).toLocaleString();$('matches').textContent=Number(state.matches||0).toLocaleString();$('rate').textContent=state.seconds>0?((state.tested||0)/state.seconds).toFixed(1):'—';$('search-status').textContent=!state.ready?'Starting engine':state.running?'Searching…':state.tested?'Search stopped':'Ready';$('start').disabled=!catalog||state.running||!chosen.size;$('stop').hidden=!state.running;$('stop').disabled=false;$('resume').hidden=state.running||!state.nextSeed;if(state.error)notice(state.error,true);renderResults()}catch(e){notice('Cannot reach the local app. Relaunch Seed Scout to reconnect.',true)}}
renderChosen();poll();const timer=setInterval(poll,1000);
